language: shell
os: linux
services:
  - docker
env:
  global:
    - IMAGE_NAME=ptr727/dwspectrum
    - IMAGE_VERSION=${TRAVIS_BUILD_ID}
    - DOWNLOAD_URL=http://updates.networkoptix.com/digitalwatchdog/29990/linux/dwspectrum-server-4.0.0.29990-linux64.deb
    - DOWNLOAD_VERSION=4.0.0.29990

before_script:
  - docker pull "${IMAGE_NAME}" || true
script:
  - docker build --pull --cache-from ${IMAGE_NAME}
    --tag ${IMAGE_NAME}:travis-latest
    --tag ${IMAGE_NAME}:travis-${IMAGE_VERSION}
    --build-arg DOWNLOAD_URL=${DOWNLOAD_URL}
    --build-arg DOWNLOAD_VERSION=${DOWNLOAD_VERSION} .
after_script:
  - docker images

before_deploy:
  - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS}
deploy:
  provider: script
  script: docker push ${IMAGE_NAME}:travis-latest && docker push ${IMAGE_NAME}:travis-${IMAGE_VERSION}
  on:
    branch: master
